sched: Properly guard when SCHED_WALT is disabled
This silences the following compilation errors:

../kernel/sched/rt.c:1777:39: error: use of undeclared identifier 'FULL_THROTTLE_BOOST'
        bool boost_on_big = sched_boost() == FULL_THROTTLE_BOOST ?
                                             ^

../kernel/sched/fair.c:6071:17: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
        struct cfs_rq *cfs_rq;
                       ^

../kernel/sched/fair.c:7883:21: error: use of undeclared identifier 'FULL_THROTTLE_BOOST'
                        sched_boost() != FULL_THROTTLE_BOOST ||
                                         ^

../kernel/sched/fair.c:9476:3: error: implicit declaration of function 'trace_sched_load_balance_skip_tasks' [-Werror,-Wimplicit-function-declaration]
                trace_sched_load_balance_skip_tasks(env->src_cpu, env->dst_cpu,
                ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>

# Conflicts:
#	kernel/sched/fair.c